apiVersion: v1
kind: PersistentVolume
metadata:
   name: miwordpress
   namespace: wordpress
spec:
   capacity:
     storage: 100Gi
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Recycle
   nfs:
     server: 172.0.0.1
     path: /nfs/wordpress