apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: miwordpress
   namespace: wordpress
   labels:
     app: wordpress
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 100Gi